import pandas as pd
df=pd.read_csv("Book1.csv",index_col="roll no")
# print(df)
# print(df.describe())
# print(df.shape)
# print("Statistical Functions")
# print("Sum=",df['marks'].sum())
# print("Mean=",df['marks'].mean())
# print("Max=",df['marks'].max())
# print("Min=",df['marks'].min())
# print("Var=",df['marks'].var())
# print("Standard Deviation=",df['marks'].std())
#print(df[df['marks']>40])
# print(df.iloc[0:3,[0,2]])
# print(df.iloc['etmr'])
print("Plotting the histogram.....")
import matplotlib.pyplot as plt
#plt.hist(df['marks'])
plt.pie(df['marks'])
plt.show()